# Assume pandoc-scholar is in the parent directory.
# Should usually be overwritten or configured via an environment variable.
PANDOC_SCHOLAR_PATH=../pandoc-scholar
ARTICLE_FILE=opz_2022.md
OUTFILE_PREFIX=opz_2022
include $(PANDOC_SCHOLAR_PATH)/Makefile
